routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return redirect()->route('recipes.index');
    });

    Route::resource('recipes', 'RecipeController');

    Route::get('/home', 'HomeController@index')->name('home');

});

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    protected $fillable =[
        'title',
        'ingredients',
        'preparation'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return redirect()->route('recipes.index');
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Recipe;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       
        return view('recipe/index', [
                'recipes' =>  Recipe::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('recipe/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate([
            'title' => 'required|string',
            'ingredients' => 'required|string',
            'preparation' => 'required|string'
        ]);
        $data = $request->all();
        
        Recipe::create([
            'title' => $data['title'],
            'ingredients' => $data['ingredients'],
            'preparation' => $data['preparation']
        ]);

        $request->session()->flash('status', 'Receita inserida com sucesso');
        return redirect()->route('recipes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('recipe/edit', [
            'recipe' => Recipe::findOrFail($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validation = $request->validate([
            'title' => 'required|string',
            'ingredients' => 'required|string',
            'preparation' => 'required|string'
        ]);
        $data = $request->all();

        Recipe::whereId($id)->update([
            'title' => $data['title'],
            'ingredients' => $data['ingredients'],
            'preparation' => $data['preparation']
        ]);

        $request->session()->flash('status', 'Receita alterada com sucesso');
        return redirect()->route('recipes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        Recipe::findOrFail($id)->delete();

        $request->session()->flash('status', 'Receita deletada com sucesso');
        return redirect()->route('recipes.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Central de Receitas</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Central de Receitas
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/recipe/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> Nova Receita</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form method="POST" action="/recipes">
                        @csrf   
                        <div class="form-group">
                            <label>Título:</label><br/>
                            <input type='text' name='title' placeholder="Título da receita" value="{{ old('title') }}" class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Ingredientes:</label><br/>
                            <textarea name='ingredients'  class="form-control" rows=3 >{{ old('ingredients') }} </textarea>  
                        </div>

                        <div class="form-group">
                            <label>Modo de preparo:</label><br/>
                            <textarea name='preparation'  class="form-control" rows=3 >{{ old('preparation') }} </textarea>
                         </div>   

                         <div class="form-group float-left">  
                            <a href="{{route('recipes.index')}}">
                                <button type="button" class="btn btn-secondary">Voltar</button>
                            </a>
                        </div>

                        <div class="form-group float-right">  
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/recipe/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> Editar Receita</div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @php
                        $title = (old('title'))? old('title') : $recipe->title;
                        $ingredients = (old('ingredients'))? old('ingredients') : $recipe->ingredients;
                        $preparation = (old('preparation'))? old('preparation') : $recipe->preparation;
                    @endphp
                    <form method="POST" action="/recipes/{{$recipe->id}}">
                        @csrf   
                        @method('PUT')
                        <div class="form-group">
                            <label>Título:</label><br/>
                            <input type='text' name='title' placeholder="Título da receita" value="{{$title}}"
                                
                             class="form-control" />
                        </div>

                        <div class="form-group">
                            <label>Ingredientes:</label><br/>
                            <textarea name='ingredients'  class="form-control" rows=3 >{{ $ingredients }} </textarea>  
                        </div>

                        <div class="form-group">
                            <label>Modo de preparo:</label><br/>
                            <textarea name='preparation'  class="form-control" rows=3 >{{ $preparation }} </textarea>
                         </div>   

                         <div class="form-group float-left">  
                            <a href="{{route('recipes.index')}}">
                                <button type="button" class="btn btn-secondary">Voltar</button>
                            </a>
                        </div>

                        <div class="form-group float-right">  
                            <button type="submit" class="btn btn-primary">Cadastrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/recipe/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Home</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class='float-right form-group'>
                        <a href="{{route('recipes.create')}}">
                            <button type="button" class="btn btn-primary"> Nova Receita</button>
                        </a>                   
                    </div>

                    <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Titulo</th>
                            <th>Ingredientes</th>
                            <th>Modo de Preparo</th>
                            <th style='width:20%'></th>
                        </tr>
                    </thead>
                 <tbody>
                 @foreach($recipes as $recipe)
                    <tr>
                        <td>{{ $recipe->id }}</td>
                        <td>{{ $recipe->title }}</td>
                        <td>{{ $recipe->ingredients }}</td>
                        <td>{{ $recipe->preparation }}</td>
                        <td>
                            <form method="POST" action="/recipes/{{$recipe->id}}"
                            onsubmit="return confirm('Tem certeza que deseja deletar esta receita ?');">
                                @csrf   
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Deletar</button>
                                <a class="btn btn-small btn-secondary" href="{{ URL::to('recipes/' . $recipe->id . '/edit') }}">Editar</a>
                            </form>          
                        </td>
                    </tr>
                @endforeach
                 </tbody>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection